// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEFvVElD85Xg95xIEjx8xHRVeNFsMGMvU',
    appId: '1:265901093184:web:b6f8fedaa8520f6826caa5',
    messagingSenderId: '265901093184',
    projectId: 'dumy-bd826',
    authDomain: 'dumy-bd826.firebaseapp.com',
    storageBucket: 'dumy-bd826.appspot.com',
    measurementId: 'G-EDBHMWPT6M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5L9Xg-gBoVdmrnaPlGsI8FdBhkrD_vSE',
    appId: '1:265901093184:android:d8fe0c3123b9c04326caa5',
    messagingSenderId: '265901093184',
    projectId: 'dumy-bd826',
    storageBucket: 'dumy-bd826.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdXWVvBs0uUoaHb5dGg9-5OMdWnBNm604',
    appId: '1:265901093184:ios:d8d4897d99e293c626caa5',
    messagingSenderId: '265901093184',
    projectId: 'dumy-bd826',
    storageBucket: 'dumy-bd826.appspot.com',
    androidClientId: '265901093184-ptvi12aslsdud7nqdgs84nsqbkevsd4d.apps.googleusercontent.com',
    iosClientId: '265901093184-6l0ca3hoks658v0574johdsmd6habl8h.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdXWVvBs0uUoaHb5dGg9-5OMdWnBNm604',
    appId: '1:265901093184:ios:ecd6ef50742e167626caa5',
    messagingSenderId: '265901093184',
    projectId: 'dumy-bd826',
    storageBucket: 'dumy-bd826.appspot.com',
    androidClientId: '265901093184-ptvi12aslsdud7nqdgs84nsqbkevsd4d.apps.googleusercontent.com',
    iosClientId: '265901093184-n4ne2ih7jmb097aseqc9d7042ejeg5uu.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
